# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = bash -c 'sleep 3; pkill -9 mako; sleep 1; /usr/bin/swaync'
exec-once = bash -c 'sleep 3; pkill swaybg; sleep 0.3; swaybg -i ~/dotfiles/wallpaper/gtr-night.jpg -m fill'
